groups:

- name: Driver

  rules:

    - alert: HighErrorRate
      expr: 'increase(hipo_driver_error_count[20m]) > 200'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: Too many errors happened (instance {{ $labels.instance }})
        description: "Error rate is too high since 30m ago.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
