groups:

- name: Driver

  rules:

    - alert: HighErrorRate
      expr: 'delta(hipo_driver_error_count[30m]) > 100'
      labels:
        severity: warning
      annotations:
        summary: Too many errors happened (instance {{ $labels.instance }})
        description: "More than 100 errors happened in last 30 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
